// src/validation/taskValidation.ts
import { z } from "zod";
// import { Database} from "./database.types";
import {
  Tables,
  //  Enums
} from "./database-generated.types";
const hasID = z.object({ id: z.string() });
// Define a Zod schema for a complete Task
export const taskSchema = z
  .object({
    title: z.string(),
    completed: z.boolean(),
  })
  .strict();

export const taskWithIdSchema = taskSchema.merge(hasID);

export type Task = z.infer<typeof taskWithIdSchema>;
export type TaskDb = Tables<"public_todos">;

// Define a Zod schema for a partial update of a Task
export const partialTaskSchema = taskSchema.partial();

export type CreateTaskDto = z.infer<typeof taskSchema>;

export type UpdateTaskDto = z.infer<typeof partialTaskSchema>;

/* Generated by GPT 
  export const taskCreateSchema = z.object({
  title: z.string(),
  description: z.string().optional(),
  completed: z.boolean().optional(),
});

export const taskUpdateSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  completed: z.boolean().optional(),
}); */
